// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDcny6ZTi6jB_gKsT1WA6m--cwtpuz99lg',
    appId: '1:118911947465:android:7b4325829a2fbe8b653318',
    messagingSenderId: '118911947465',
    projectId: 'namaz-traker',
    storageBucket: 'namaz-traker.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyArq13xJlA0X2IJU57F3S9MyZEIYTwEyog',
    appId: '1:118911947465:ios:77cabb9675243271653318',
    messagingSenderId: '118911947465',
    projectId: 'namaz-traker',
    storageBucket: 'namaz-traker.appspot.com',
    iosBundleId: 'com.example.habo',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyArq13xJlA0X2IJU57F3S9MyZEIYTwEyog',
    appId: '1:118911947465:ios:cea8ff4cbfc0489d653318',
    messagingSenderId: '118911947465',
    projectId: 'namaz-traker',
    storageBucket: 'namaz-traker.appspot.com',
    iosBundleId: 'com.example.habo.RunnerTests',
  );
}
